/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../../../../encoder';

import { Observable }                                        from 'rxjs/Observable';



import { BaseProduct } from '../models/baseProduct';
import { CreatePromotionDTO } from '../models/createPromotionDTO';

import { BASE_PATH, COLLECTION_FORMATS }                    from '../../../../variables';
import { Configuration }                                     from '../../../../configuration';

@Injectable()
export class AddPromotionControllerService {

    protected basePath = 'http://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * create
     * 
     * @param createPromotionDTO createPromotionDTO
     * @param idCommercant idCommercant
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUsingPOST(createPromotionDTO: CreatePromotionDTO, idCommercant: number, observe?: 'body', reportProgress?: boolean): Observable<CreatePromotionDTO>;
    public createUsingPOST(createPromotionDTO: CreatePromotionDTO, idCommercant: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CreatePromotionDTO>>;
    public createUsingPOST(createPromotionDTO: CreatePromotionDTO, idCommercant: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CreatePromotionDTO>>;
    public createUsingPOST(createPromotionDTO: CreatePromotionDTO, idCommercant: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (createPromotionDTO === null || createPromotionDTO === undefined) {
            throw new Error('Required parameter createPromotionDTO was null or undefined when calling createUsingPOST.');
        }
        if (idCommercant === null || idCommercant === undefined) {
            throw new Error('Required parameter idCommercant was null or undefined when calling createUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<CreatePromotionDTO>(`${this.basePath}/api/addpromotion/create/${encodeURIComponent(String(idCommercant))}`,
            createPromotionDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * referenceProductList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public referenceProductListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<BaseProduct>>;
    public referenceProductListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BaseProduct>>>;
    public referenceProductListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BaseProduct>>>;
    public referenceProductListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<BaseProduct>>(`${this.basePath}/api/addpromotion/productList`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
