/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../../../../encoder';

import { Observable }                                        from 'rxjs';

import { CategoryProduct } from '../models/categoryProduct';
import { Promotion } from '../models/promotion';
import { RequestSearchDTO } from '../models/requestSearchDTO';
import { ResultSearchDTO } from '../models/resultSearchDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../../../../variables';
import { Configuration }                                     from '../../../../configuration';


@Injectable()
export class CatalogControllerService {

    protected basePath = 'http://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * initCatalogProduits
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public initCatalogProduitsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Promotion>>;
    public initCatalogProduitsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Promotion>>>;
    public initCatalogProduitsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Promotion>>>;
    public initCatalogProduitsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Promotion>>(`${this.basePath}/api/catalog/allPromotions`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * initComboboxCategorie
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public initComboboxCategorieUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CategoryProduct>>;
    public initComboboxCategorieUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CategoryProduct>>>;
    public initComboboxCategorieUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CategoryProduct>>>;
    public initComboboxCategorieUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<CategoryProduct>>(`${this.basePath}/api/catalog/allCategories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search
     * 
     * @param requestSearchDTO requestSearchDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchUsingPOST(requestSearchDTO: RequestSearchDTO, observe?: 'body', reportProgress?: boolean): Observable<ResultSearchDTO>;
    public searchUsingPOST(requestSearchDTO: RequestSearchDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResultSearchDTO>>;
    public searchUsingPOST(requestSearchDTO: RequestSearchDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResultSearchDTO>>;
    public searchUsingPOST(requestSearchDTO: RequestSearchDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (requestSearchDTO === null || requestSearchDTO === undefined) {
            throw new Error('Required parameter requestSearchDTO was null or undefined when calling searchUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<ResultSearchDTO>(`${this.basePath}/api/catalog/research`,
            requestSearchDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
