/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../../../../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Reservation } from '../models/reservation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../../../../variables';
import { Configuration }                                     from '../../../../configuration';


@Injectable()
export class ReservationManagementControllerService {

    protected basePath = 'http://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getReservationList
     * 
     * @param idCommercant idCommercant
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getReservationListUsingGET(idCommercant: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Reservation>>;
    public getReservationListUsingGET(idCommercant: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Reservation>>>;
    public getReservationListUsingGET(idCommercant: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Reservation>>>;
    public getReservationListUsingGET(idCommercant: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (idCommercant === null || idCommercant === undefined) {
            throw new Error('Required parameter idCommercant was null or undefined when calling getReservationListUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Reservation>>(`${this.basePath}/api/reservationManagement/reservationList/${encodeURIComponent(String(idCommercant))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * validateReservation
     * 
     * @param idReservation idReservation
     * @param withDrawalCode withDrawalCode
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validateReservationUsingPOST(idReservation: number, withDrawalCode: string, observe?: 'body', reportProgress?: boolean): Observable<Reservation>;
    public validateReservationUsingPOST(idReservation: number, withDrawalCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Reservation>>;
    public validateReservationUsingPOST(idReservation: number, withDrawalCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Reservation>>;
    public validateReservationUsingPOST(idReservation: number, withDrawalCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (idReservation === null || idReservation === undefined) {
            throw new Error('Required parameter idReservation was null or undefined when calling validateReservationUsingPOST.');
        }
        if (withDrawalCode === null || withDrawalCode === undefined) {
            throw new Error('Required parameter withDrawalCode was null or undefined when calling validateReservationUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<Reservation>(`${this.basePath}/api/reservationManagement/reservation/${encodeURIComponent(String(idReservation))}/${encodeURIComponent(String(withDrawalCode))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
