/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';
import { City } from './city';
import { GeographicCoordinates } from './geographicCoordinates';


export interface Address {
    addressType?: AddressType;
    city?: City;
    complement?: string;
    coordinates?: GeographicCoordinates;
    id?: number;
    name?: string;
    number?: number;
}
