/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Promotion } from './promotion';
import { ReferenceProduct } from './referenceProduct';


export interface BaseProduct {
    addDate?: Date;
    baseProduct?: BaseProduct;
    description?: string;
    id?: number;
    image?: string;
    initPrice?: number;
    lastProduct?: Product;
    promotion?: Promotion;
    promotionList?: Array<Promotion>;
    referenceProduct?: ReferenceProduct;
    removeDate?: Date;
    type?: string;
}
