/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CreatePromotionDTO {
    description?: string;
    discountValue?: number;
    idCommerce?: number;
    isCumulative?: boolean;
    minPurchaseAmountDiscount?: number;
    minPurchaseAmountPercent?: number;
    numberOffered?: number;
    numberPurchase?: number;
    percentValue?: number;
    productId?: number;
    productTakeAwayDuration?: number;
    promotionDuration?: number;
    promotionName?: string;
    quantityInitAvailable?: number;
    typePromotion?: string;
}
