/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Promotion } from './promotion';
import { ReferenceProduct } from './referenceProduct';


export interface Product {
    id?: number;
    image: string;
    lastProduct?: Product;
    promotion?: Promotion;
    referenceProduct?: ReferenceProduct;
}
