/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseProduct } from './baseProduct';
import { Duration } from './duration';
import { Product } from './product';
import { PromotionType } from './promotionType';
import { Publish } from './publish';
import { Shop } from './shop';


export interface Promotion {
    baseProduct?: BaseProduct;
    dateCreation?: Date;
    dateRemove?: Date;
    description?: string;
    endDate?: Date;
    id?: number;
    initPrice?: number;
    isCumulative?: boolean;
    lastProduct?: Product;
    limitTimePromotion?: Duration;
    limitTimeTakePromotion?: Duration;
    name?: string;
    priceAfterPromotion?: number;
    product?: Product;
    promotion?: Promotion;
    promotionList?: Array<Promotion>;
    promotionType?: PromotionType;
    publish?: Publish;
    quantityInitAvailable?: number;
    quantityRemaining?: number;
    shopList?: Array<Shop>;
    shops?: { [key: string]: Shop; };
}
