/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryProduct } from './categoryProduct';
import { SalesUnit } from './salesUnit';


export interface ReferenceProduct {
    categoriesProduct?: CategoryProduct;
    dateDeferencing?: Date;
    dateReferencing?: Date;
    id?: number;
    name?: string;
    salesUnit?: SalesUnit;
    type?: string;
}
