/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ShopRegistration {
    deregistrationDate?: Date;
    deregistrationMotive?: ShopRegistration.DeregistrationMotiveEnum;
    id?: number;
    registrationDate?: Date;
}
export namespace ShopRegistration {
    export type DeregistrationMotiveEnum = 'SATISFACTION' | 'INTEREST' | 'ERGONOMICS';
    export const DeregistrationMotiveEnum = {
        SATISFACTION: 'SATISFACTION' as DeregistrationMotiveEnum,
        INTEREST: 'INTEREST' as DeregistrationMotiveEnum,
        ERGONOMICS: 'ERGONOMICS' as DeregistrationMotiveEnum
    }
}
